# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200601_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post/'),
            preserve_default=False,
        ),
    ]
