# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
            preserve_default=False,
        ),
    ]
